version: "3.0"

services:
    databse:
        container_name: core_pg_db
        image: postgres:16-alpine
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ../database/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: wisee

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "default@wisee.com"
            PGADMIN_DEFAULT_PASSWORD: "default"
        ports:
            - "54321:80"

volumes:
    pgdata:
