name: "wisee-backend"

services:
    wisee-DB:
        image: postgres:latest
        ports:
            - "7856:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: wisee
