name: Tests

on:
    pull_request:
        branches: ["*"]

jobs:
    tests:
        runs-on: ubuntu-latest
        
        services:
          postgres:
            image: postgres:latest
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: wisee_core_test
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        name: Run tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: "./go.mod"

            - run: go version

            - name: Copy Env
              run: cp ./environments/test.env .env

            - name: Run Unit tests
              run: ENV=test go test ./tests/unit -v

            - name: Run Integration tests
              run: ENV=test go test ./tests/integration -v
